apiVersion: v1
kind: ConfigMap
metadata:
  name: jobability-config
  namespace: jobability
data:
  DJANGO_DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_USE_SQLITE: "False"
  POSTGRES_DB: jobability
  POSTGRES_USER: jobability
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  DJANGO_USE_REDIS_SESSIONS: "False"
  DJANGO_USE_MINIO: "False"
  CORS_ALLOWED_ORIGINS: ""
  CSRF_TRUSTED_ORIGINS: ""
