apiVersion: v1
kind: ConfigMap
metadata:
  name: jobability-config
  namespace: jobability
data:
  DJANGO_DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_USE_SQLITE: "False"
  POSTGRES_DB: jobability
  POSTGRES_USER: jobability
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  DJANGO_USE_REDIS_SESSIONS: "True"
  REDIS_URL: "redis://redis:6379/1"
  DJANGO_USE_MINIO: "True"
  MINIO_ENDPOINT: "http://minio:9000"
  MINIO_BUCKET: jobability
  MINIO_PUBLIC_MEDIA_URL: "/media/"
  CORS_ALLOWED_ORIGINS: ""
  CSRF_TRUSTED_ORIGINS: ""
